name: WakaTime Stats (Image)

on:
  schedule:
    # Her 12 saatte bir çalışır
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Generate WakaTime Image
    runs-on: ubuntu-latest
    permissions:
      contents: write # Yazma izni şart
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg # Bu isimde bir resim oluşturacak
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }} # Senin kaydettiğin anahtarı kullanır
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_limit: 5
          config_theme: dracula # Senin temana uygun
          config_padding: 0, 8
          config_display: large