name: WakaTime Stats (Graph)

on:
  schedule:
    # Her 6 saatte bir güncellensin
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Generate WakaTime Graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "" # Gereksiz başlıkları kapatır
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, languages, languages-graphs
          plugin_wakatime_limit: 4
          # GÖRÜNÜM AYARLARI (DÜZELTME)
          config_theme: dracula # Senin temanla uyumlu parlak renkler
          config_display: regular # Büyük görünüm
          config_padding: 0, 10