name: WakaTime Terminal Graph

on:
  schedule:
    # Her 4 saatte bir güncellensin
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Generate Terminal Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: wakatime-terminal.svg # Resim dosyası oluşturacak
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "" # Başlıkları kapat, sadece grafik olsun
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, languages, languages-graphs
          plugin_wakatime_limit: 5
          
          # --- TASARIM AYARLARI (TERMİNAL GÖRÜNÜMÜ) ---
          config_theme: dracula # Senin teman
          config_display: large # Geniş görünüm
          config_padding: 0, 8 # Kenar boşluklarını ayarla
